# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "daemon-spawn"
  s.version = "0.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Vollmer", "Seamus Abshere", "Emmanual Gomez", "Seth Falcon", "Woody Peterson", "Tilo Pr\u{fc}tz", "Romain Champourlier"]
  s.date = "2013-01-04"
  s.description = "With daemon-spawn you can start, stop and restart processes that run\n    in the background. Processed are tracked by a simple PID file written\n    to disk."
  s.email = "romain@softr.li"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    "History.txt",
    "Manifest.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "daemon-spawn.gemspec",
    "lib/daemon_spawn.rb",
    "test/daemon_spawn_test.rb",
    "test/multi_daemon_spawn_test.rb",
    "test/servers/deaf_server.rb",
    "test/servers/echo_server.rb",
    "test/servers/simple_server.rb",
    "test/servers/stubborn_server.rb",
    "test/servers/taps_server.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/rchampourlier/daemon-spawn"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Daemon launching and management made dead simple [rchampourlier's fork]"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

